apivideo/api.video-documentation

vod/add-captions.md

Changes are for [this Asana task](https://app.asana.com/0/1204307844224163/1206003116770297).
**Summary**: I updated the description of the `language` parameter on the [Adding captions](https://docs.api.video/vod/add-captions) page.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206003116770302

Update Captions guide

---

sdks/nocode/contentful.md
sdks/nocode/strapi.md
sdks/nocode/wordpress.md
sdks/nocode/zapier.md

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1206048315667454).
**Summary**
- Added available getting started videos ([Notion](https://www.notion.so/apivideo/No-code-integrations-e1b7bd3ca0064961a2b44562bc42674d)) to the [no-code integration guides](https://docs.api.video/sdks/nocode)
- Updated the Zapier guide with internal links
- fixed some wording issues

Add nocode videos to docs

---

live-streaming/create-a-live-stream.md

Changes are for [this Asana task](https://app.asana.com/0/1204370684353095/1206055648190037).
**Summary**:
- added [this video](https://embed.api.video/vod/vi6mgcrUqQuLyQNRW0qbl6gt) to the [Live stream quickstart page](https://docs.api.video/live-streaming/create-a-live-stream)
- fixed wording

Add live stream quickstart video

---

reference/README.md
vod/video-best-practices.md

Changes are for [this Asana task](https://app.asana.com/0/1204370684353095/1206228951687870).
**Summary**:
* updated all mentions of video file size limit from 20 GiB to 30 GiB
* Affected pages: 
* https://docs.api.video/vod/video-best-practices
* https://docs.api.video/reference

Update video size limit to 30 GiB

---

live-streaming/live-stream-best-practices.md

Changes are for [this Asana task](https://app.asana.com/0/1204307844224163/1205634133195419).
**Summary**:
* added short explanation about DVR to the [Live stream best practices](https://docs.api.video/live-streaming/live-stream-best-practices) page
* updated DVR duration limit to 1 hour

Add DVR info to live stream best practices

---

reference/README.md

I found that the URL that points to our OpenAPI spec was outdated - fixed it so now it points to the Docs repo.

Update OpenAPI spec url

---

live-streaming/restreams.md

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1206984136702496).
**Summary**
Looks like Facebook only accepts RTMPS for restreaming. I removed it from the list of supported platforms from the [Restreaming guide](https://docs.api.video/live-streaming/restreams#supported-platforms).

Remove mentions of Facebook from restreams docs

---

reference/README.md
reference/general-errors.md
reference/too-many-requests.md

⚠️ **This PR should not be merged before API rate limiting is released** ⚠️
Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1207037975949562).
Docs drafts are [here](https://www.notion.so/apivideo/API-rate-limiting-2ef948077a3748298c34be56a254578e).
**Summary**
* added information about API rate limiting to the API reference's [Limitation](https://docs.api.video/reference#limitation) section
* added the 429 - Too many requests error to [General errors](https://docs.api.video/reference/general-errors) as a sub-page (the API will point to this page in the error response's `type` field)
⚠️ **This PR should not be merged before API rate limiting is released** ⚠️

Add information about rate limiting

---

live-streaming/create-a-live-stream.md
live-streaming/live-stream-best-practices.md

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1207117675124006).
**Summary**
Added these to the docs:
- A callout that both `RTMP` and `SRT` are available protocols, in the [Getting started](https://docs.api.video/live-streaming/create-a-live-stream) page for Live streaming.
- A short explanation on which protocol is recommended in which situations, in the [Live Streaming best practices](https://docs.api.video/live-streaming/live-stream-best-practices)
- A table that lists the streaming URLs that we have, in the [Live Streaming best practices](https://docs.api.video/live-streaming/live-stream-best-practices) page
- Guidance steps on how to configure a live stream using `SRT` in the Live Streaming getting started …

Update live streaming docs with SRT

---

_assets/css/style.css

Quick fix to remove a font-size override that was left over from the previous docs version.

Remove font size override

---

delivery-analytics/analytics.md
doctave.yaml
openapi.yaml
reference/navigation.yaml

Context: https://api-video.slack.com/archives/C01HRNQKC2K/p1720184092960169?thread_ts=1720182120.585669&cid=C01HRNQKC2K
**Summary**
- remove mentions of `v2` in the context of Analytics
- remove paragraph about migrating from v1 to v2 for Analytics

Remove v2 and migration paragraph

---

delivery-analytics/analytics.md
openapi.yaml

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1207795165508758).
**Summary**
- Added the `/data/buckets/play-total/media-id` route to the `/data/buckets/{metric}/{breakdown}` endpoint
- Added a use case example for `play-total` + `media-id`
Also incorporated changes from  Guillaume’s feedback here: [Analytics docs feedbacks](https://www.notion.so/Analytics-docs-api-video-feedbacks-8888607108534cf38f440d5bccf22ec1?pvs=21)
- removed unnecessary paragraph
- fixed typo
**Not part of this PR**
Started vote on moving Analytics docs to a standalone tab: https://api-video.slack.com/archives/C01HRNQKC2K/p1721056171869069
- this will be done in a separate PR ⚠️

Update Analytics docs

---

doctave.yaml
openapi.yaml
reference/attribute-required.md
reference/authentication-invalid-upload-token.md
reference/authentication-invalid-user-credentials.md
reference/navigation.yaml
reference/uploaded-file-extension-invalid.md

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1207795160247631).
**Summary**
- the OpenAPI specification still had some old links in the ReadMe path format. I added redirects from all old URLs to the new ones: from `docs.api.video/docs/*` to `docs.api.video/reference/*`. 
- in some cases, there was no content that could be directly mapped, so I created these error pages:
-  `reference/attribute-required.md`
-  `reference/uploaded-file-extension-invalid.md`
-  `reference/authentication-invalid-user-credentials.md`
@ThibaultBee after a discussion with @olivierapivideo , I am making this change directly on the OpenAPI spec in the `documentation` repo. Olivier will move all changes to the client-generator repo to avoid a bunch of conflicts. ⚠️

Add new error pages and fix URLs

---

live-streaming/create-a-live-stream.md
live-streaming/live-stream-best-practices.md

Context: https://api-video.slack.com/archives/C02CW29KJ/p1721146667846479
**Summary**
I removed mentions of "beta" where we talk about the SRT protocol.

Remove beta mentions from SRT

---

live-streaming/create-a-live-stream.md
live-streaming/live-stream-best-practices.md
live-streaming/restreams.md
openapi.yaml

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1207827750013046).
**Summary**
I added mentions of the RTMPS streaming protocol for ingestion and restreaming. Affected pages:
- Live streaming quickstart
- Live streaming best practices
- Restreaming guide
I also updated the OpenAPI spec so it mentions RTMPS.
⚠️ **Some notes** ⚠️ 
- This PR should only be merged when all changes (API, ingestion pipeline, dashboard) are done.
- ~~I do not know if the API is updated or not - we used to have error handling for restreaming hardcoded to only accept `rtmp`! This should be checked.~~ It is done on API side, context [here](https://api-video.slack.com/archives/C04H2LRGF29/p1721199040069359?thread_ts=1721169008.681159&cid=C04H2LRGF29). ✅

Add RTMPS streaming protocol to docs

---

doctave.yaml

Context on [Slack](https://api-video.slack.com/archives/C01L45802S2/p1721394234918299).
I added a missing redirect from the old ReadMe path format to the new Analytics landing page in the docs. This fixes a possible `404`.

Add redirect to analytics page

---

live-streaming/working-with-live-streams.md
openapi.yaml

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1207866972528499).
**Summary**
- added `PUT /live-streams/{liveStreamId}/complete` to the OpenAPI spec
- added information about the endpoint to the [Working with live streams](https://docs.api.video/live-streaming/working-with-live-streams) guide

Add live stream completed endpoint

---

live-streaming/restreams.md

Removing the beta callout from the Restreaming guide, as this feature is no longer in beta.

Remove beta callout

---

analytics/migration.md
analytics/navigation.yaml

**Summary**
I added a migration guide that explains the actions clients will need to take in case they are already using the current analytics solution via player + analytics SDK, or via API.
Source on [Slack](https://api-video.slack.com/archives/C061BVDEUCS/p1721643159117509).
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207865842430915

Add analytics migration guide to docs

---

openapi.yaml

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1208062878184817).
**Summary**:
Added `sortBy` and `sortOrder` query parameters to these Analytics endpoints:
- `/data/timeseries/{metric}`
- `/data/buckets/{metric}/{breakdown}`

Add sortBy and sortOrder parametes to analytics

---

admin-api.yaml
reference/admin-api-overview.md
reference/navigation.yaml

Changes are for [this Asana task](https://app.asana.com/0/1205386992201973/1208156805425346).
**Summary**
* added the new usage endpoints under the `Usage` tag to the OpenAPI spec
* added explanation about the new endpoints to the Admin API overview page
⚠️ Due to a limitation in the OpenAPI 3.0 specification, the `{date}` object key for both endpoints' responses is described without the `pattern` tag. There is an ongoing discussion about this at the time I am opening this PR. ⚠️ I'll add the outcome in a comment.

Add usage endpoints to Admin api

---

reference/admin-api-overview.md

Following up on a change discussed in [this Slack thread](https://api-video.slack.com/archives/C04H2LRGF29/p1726041322190549) - this missing paragraph was left out of the earlier batch of changes.
It adds some context on how to interact with the Admin API, and also fixes the indents of JSON responses.

Re-add missing paragraph

---

live-streaming/list-live-streams.md
openapi.yaml
vod/add-a-thumbnail-to-your-video.md
vod/delegated-upload-tokens.md
vod/delete-a-video.md
vod/video-best-practices.md

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1208125970959632).
**Summary**
* added information about the feature to the [Delete a video](https://docs.api.video/vod/delete-a-video) and [Video best practices](https://docs.api.video/vod/video-best-practices) guides.
* added some missing internal links to the API reference in the [Delete a video](https://docs.api.video/vod/delete-a-video) guide
* updated the API reference 👇 
**OpenAPI changes**
* added the new query parameter `removed` to `GET /videos` 
* added the new body parameter `removed` to `PATCH /videos/{videoId}`
* added new fields `deletesAt` and `removedAt` to the `video` response object
* updated the description of all date-time fields in the `video` response object to show ATOM format
* removed …

Add Video Restore feature to docs

---

analytics/overview.md
openapi.yaml

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1208318311784939).
**Summary**
- added mention of the Analytics addon that enables 3 months or 12 months of data retention
- updated both the Analytics guide and the API reference

Add mention of the extended data retention for analytics

---

openapi.yaml
reference/create-and-manage-webhooks.md

Changes are for [this Asana task](https://app.asana.com/0/1204307844224163/1208357061185849).
**Summary**
* Added the new field `signatureSecret` to the webhook creation's response schema and the response examples
* Updated descriptions for the webhook endpoints' responses
* Revamped the Webhooks guide to have a more logical structure
* Added the webhook signature validation process and a sample implementation to the Webhooks guide
* Added all webhook notifications to the OpenAPI specification under `x-webhooks`, and included the new webhook headers

Add webhook signatures to documentation

---

reference/navigation.yaml

Add missing OpenAPI tag for the `/tags` endpoint, so it is visible in the API reference's navigation sidebar.

Add missing tag

---

vod/create-summaries.md

Quick fix in the Summary guide:
- removed unnecessary indefinite article `an`
- updated `title` tag from Create to Generate

Fix typo and title tag

---

analytics/overview.md

Changes are for these Asana tasks:
* [Task about new metrics](https://app.asana.com/0/1205634133195403/1208145821422434)
* [Task about explaining the difference between timeseries and aggregations](https://app.asana.com/0/1205634133195403/1208119928333952)
**Summary**
- Reorganized the Analytics guide to focus more on usage and examples
- Added new use cases based on the new metrics
- Added explanation about user sessions
- Added detailed explanation about the difference between the `/data/metrics/{metric}/{aggregation}` and `/data/timeseries/{metric}` endpoints

Add new information to Analytics guide

---

reference/summary-already-exists.md
vod/create-summaries.md

Changes are for these Asana tasks:
* [Remove summary title](https://app.asana.com/0/1205386992201973/1208697246097961)
* [Select summary attributes individually](https://app.asana.com/0/1205386992201973/1208647488270061)
**Summary** 🤖 
* Remove mentions of the `title` attribute of summary sources
* Add explanation of new parameters that enable summary creation with individual attributes
* Update the [Summaries](https://docs.api.video/vod/create-summaries) guide to explain the new behavior when creating or updating summaries
* Update [Summary already exists](https://docs.api.video/reference/summary-already-exists) error page with the new behavior

Add new information about summaries

---

openapi.yaml

> Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1208756299627438).
**Summary**
- Added the new webhooks: `video.caption.generated` and `video.summary.generated`
- Updated the Create Webhook endpoint description, request schema, and response schema to list the webhook events as enums for the `events` field
- Added link to Transcript guide in the description for the `generationMode` attribute
> Created by @olivier-lando via https://github.com/apivideo/api.video-api-client-generator/pull/408

Add new webhooks
